Update plugins publish workflow to check for pre-releases (#61)

diff --git a/.github/workflows/registry-publish-ghcr.yml b/.github/workflows/registry-publish-ghcr.yml
--- a/.github/workflows/registry-publish-ghcr.yml
+++ b/.github/workflows/registry-publish-ghcr.yml
@@ -63,14 +63,14 @@ jobs:
           echo $trim
           echo "VERSION=${trim}" >> $GITHUB_ENV
 
-      # - name: Validate Version String is SemVer
-      #   run: |-
-      #     if [[ $VERSION =~  ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-      #       echo "Version OK: $VERSION"
-      #     else
-      #       echo "Invalid version: $VERSION"
-      #       exit 1
-      #     fi
+      - name: Validate Version String is not pre-release
+        run: |-
+          if [[ $VERSION =~  ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Version OK: $VERSION"
+          else
+            echo "Invalid version: $VERSION"
+            exit 1
+          fi
 
       - name: Ensure Version Does Not Exist
         run: |-
