Add darwin amd64 installation tests

diff --git a/.github/workflows/steampipe-anywhere.yml b/.github/workflows/steampipe-anywhere.yml
--- a/.github/workflows/steampipe-anywhere.yml
+++ b/.github/workflows/steampipe-anywhere.yml
@@ -414,6 +414,7 @@ jobs:
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
           echo $plugin_name
           echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV
+
       - name: Check out steampipe-postgres-fdw-anywhere
         uses: actions/checkout@v3
         with:
@@ -675,6 +676,7 @@ jobs:
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
           echo $plugin_name
           echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV
+
       - name: Check out steampipe-sqlite-extension
         uses: actions/checkout@v3
         with:
@@ -1108,8 +1110,8 @@ jobs:
             exit 1  # This exits the step with an error status, failing the job
           fi
 
-  check-installation-darwin:
-    name: Check Installation(Darwin)
+  check-installation-darwin-arm64:
+    name: Check Installation(Darwin ARM64)
     runs-on: macos-latest
     needs: build-draft-release
     steps:
@@ -1177,3 +1179,74 @@ jobs:
             echo "Version does not match. Expected was $EXPECTED_OUTPUT, but got $COMMAND_OUTPUT."
             exit 1  # This exits the step with an error status, failing the job
           fi
+
+  check-installation-darwin-amd64:
+    name: Check Installation(Darwin AMD64)
+    runs-on: macos-13
+    needs: build-draft-release
+    steps:
+      - name: Check architecture
+        run: uname -a
+
+      - name: Set environment variables
+        run: |
+          plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
+          echo $plugin_name
+          echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV
+
+      - name: Get latest version tag
+        run: |-
+          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+          echo "Version: ${VERSION}"
+
+      - name: Install PostgreSQL14
+        run: brew install postgresql@14
+
+      - name: Start PostgreSQL service
+        run: brew services start postgresql@14
+
+      - name: Check pg_config version
+        run: pg_config --version
+
+      - name: Download and install Postgres FDW
+        run: |-
+          curl -fsSL -o install_postgres_fdw.sh https://steampipe.io/install/postgres.sh
+          echo | sudo -E TERM=xterm bash install_postgres_fdw.sh ${{ env.PLUGIN_NAME }} latest 2>/dev/null
+          rm -f install_postgres_fdw.sh
+
+      - name: Configure PostgreSQL
+        run: |-
+          psql -d postgres -c "CREATE EXTENSION IF NOT EXISTS steampipe_postgres_${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "CREATE SERVER steampipe_${{ env.PLUGIN_NAME }} FOREIGN DATA WRAPPER steampipe_postgres_${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "CREATE SCHEMA ${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "IMPORT FOREIGN SCHEMA ${{ env.PLUGIN_NAME }} FROM SERVER steampipe_${{ env.PLUGIN_NAME }} INTO ${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "SELECT * FROM pg_extension;"
+
+      - name: Download and install SQLite Extension
+        run: |-
+          echo | TERM=xterm bash <(curl -fsSL https://steampipe.io/install/sqlite.sh) ${{ env.PLUGIN_NAME }} latest 2>/dev/null
+
+      - name: Download and install Export Tool
+        run: |-
+          curl -fsSL -o install_export.sh https://steampipe.io/install/export.sh
+          echo | sudo -E TERM=xterm bash install_export.sh ${{ env.PLUGIN_NAME }} latest 2>/dev/null
+          rm -f install_export.sh
+
+      - name: Test Export Tool
+        run: |
+          # Define the expected output based on environment variables and inputs
+          EXPECTED_OUTPUT="steampipe_export_${{ env.PLUGIN_NAME }} ${VERSION}"
+          echo "Expected version output: $EXPECTED_OUTPUT"
+          
+          # Execute the command to get the actual version output
+          COMMAND_OUTPUT=$(steampipe_export_${{ env.PLUGIN_NAME }} --version)
+          echo "Actual command output version: $COMMAND_OUTPUT"
+          
+          # Compare the actual output with the expected output
+          if [ "$COMMAND_OUTPUT" == "$EXPECTED_OUTPUT" ]; then
+            echo "Version matches."
+          else
+            echo "Version does not match. Expected was $EXPECTED_OUTPUT, but got $COMMAND_OUTPUT."
+            exit 1  # This exits the step with an error status, failing the job
+          fi
+        
