Use macos-13 runners to build Darwin AMD64 binaries and use Linux ARM64 runner group (#34)

diff --git a/.github/workflows/steampipe-anywhere.yml b/.github/workflows/steampipe-anywhere.yml
--- a/.github/workflows/steampipe-anywhere.yml
+++ b/.github/workflows/steampipe-anywhere.yml
@@ -45,6 +45,9 @@ jobs:
     runs-on: ubuntu-20.04
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -117,32 +120,74 @@ jobs:
     name: Build Postgres 14 FDW for Linux - ARM64
     needs: get-version
     runs-on: 
-      group: steampipe-darwin-arm-runners
+      group: linux-arm64-runners
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
           echo $plugin_name
           echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV
-      - name: Check out steampipe-postgres-fdw-anywhere
-        uses: actions/checkout@v3
+    
+      - name: Check out steampipe-postgres-fdw
+        uses: actions/checkout@v2
         with:
           repository: "turbot/steampipe-postgres-fdw"
           ref: main
 
-      - name: Check docker images available in runner
-        run: docker images
+      - name: Setup GoLang
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.21
 
-      - name: Run build script
+      - name: Setup apt-get
+        run: |-
+          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
+          sudo env ACCEPT_EULA=Y apt-get update
+          sudo env ACCEPT_EULA=Y apt-get upgrade
+
+      - name: Install PostgreSQL14 Dev
+        run: |-
+          sudo apt-get -y install postgresql-server-dev-14
+
+      - name: Find stuff and set env
+        run: |-
+
+          which pg_config
+          pg_config --version
+
+          export PATH=$(pg_config --bindir):$PATH
+          export PGXS=$(pg_config --pgxs)
+
+          export SERVER_LIB=$(pg_config --includedir)/14/server
+          export INTERNAL_LIB=$(pg_config --includedir)/internal
+
+          export CFLAGS="$(pg_config --cflags) -I${SERVER_LIB} -I${INTERNAL_LIB} -g"
+          export PG_CFLAGS="$(pg_config --cflags) -I${SERVER_LIB} -I${INTERNAL_LIB} -g"
+
+          export LDFLAGS=$(pg_config --ldflags)
+          export PG_LDFLAGS=$(pg_config --ldflags)
+
+          ls -la $SERVER_LIB
+          ls -la $INTERNAL_LIB
+
+      - name: Build steampipe-postgres-fdw-anywhere
         run: |
-          chmod +x ./scripts/build-linux-arm-pg14.sh
-          bash ./scripts/build-linux-arm-pg14.sh ${{ env.PLUGIN_NAME }}
-      
-      - name: Check if binaries are available
-        run: ls -l $GITHUB_WORKSPACE
+          pwd
+          ls -ltr
+          make standalone plugin=${{ env.PLUGIN_NAME }}
+          ls -ltr
 
-      - name: Save Linux Build Artifact - AMD64
+      - name: Rename and zip the build-Linux folder
+        run: |-
+          mv build-Linux steampipe_postgres_${{ env.PLUGIN_NAME }}.pg14.linux_arm64
+          tar -czvf steampipe_postgres_${{ env.PLUGIN_NAME }}.pg14.linux_arm64.tar.gz steampipe_postgres_${{ env.PLUGIN_NAME }}.pg14.linux_arm64
+
+      - name: Save Linux Build Artifact - ARM64
         uses: actions/upload-artifact@v3
         with:
           name: steampipe_postgres_${{ env.PLUGIN_NAME }}.pg14.linux_arm64.tar.gz
@@ -152,8 +197,11 @@ jobs:
   build-postgres-14-fdw-osx-amd64:
     name: Build Postgres 14 FDW for Darwin - AMD64
     needs: get-version
-    runs-on: macos-latest
+    runs-on: macos-13
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -233,6 +281,9 @@ jobs:
     needs: get-version
     runs-on: macos-14
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -316,6 +367,9 @@ jobs:
     runs-on: ubuntu-20.04
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -388,32 +442,74 @@ jobs:
     name: Build Postgres 15 FDW for Linux - ARM64
     needs: get-version
     runs-on: 
-      group: steampipe-darwin-arm-runners
+      group: linux-arm64-runners
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
           echo $plugin_name
           echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV
-      - name: Check out steampipe-postgres-fdw-anywhere
-        uses: actions/checkout@v3
+
+      - name: Check out steampipe-postgres-fdw
+        uses: actions/checkout@v2
         with:
           repository: "turbot/steampipe-postgres-fdw"
           ref: main
 
-      - name: Check docker images available in runner
-        run: docker images
+      - name: Setup GoLang
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.21
 
-      - name: Run build script
+      - name: Setup apt-get
+        run: |-
+          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
+          sudo env ACCEPT_EULA=Y apt-get update
+          sudo env ACCEPT_EULA=Y apt-get upgrade
+
+      - name: Install PostgreSQL15 Dev
+        run: |-
+          sudo apt-get -y install postgresql-server-dev-15
+
+      - name: Find stuff and set env
+        run: |-
+
+          which pg_config
+          pg_config --version
+
+          export PATH=$(pg_config --bindir):$PATH
+          export PGXS=$(pg_config --pgxs)
+
+          export SERVER_LIB=$(pg_config --includedir)/15/server
+          export INTERNAL_LIB=$(pg_config --includedir)/internal
+
+          export CFLAGS="$(pg_config --cflags) -I${SERVER_LIB} -I${INTERNAL_LIB} -g"
+          export PG_CFLAGS="$(pg_config --cflags) -I${SERVER_LIB} -I${INTERNAL_LIB} -g"
+
+          export LDFLAGS=$(pg_config --ldflags)
+          export PG_LDFLAGS=$(pg_config --ldflags)
+
+          ls -la $SERVER_LIB
+          ls -la $INTERNAL_LIB
+
+      - name: Build steampipe-postgres-fdw-anywhere
         run: |
-          chmod +x ./scripts/build-linux-arm-pg15.sh
-          bash ./scripts/build-linux-arm-pg15.sh ${{ env.PLUGIN_NAME }}
-      
-      - name: Check if binaries are available
-        run: ls -l $GITHUB_WORKSPACE
+          pwd
+          ls -ltr
+          make standalone plugin=${{ env.PLUGIN_NAME }}
+          ls -ltr
 
-      - name: Save Linux Build Artifact - AMD64
+      - name: Rename and zip the build-Linux folder
+        run: |-
+          mv build-Linux steampipe_postgres_${{ env.PLUGIN_NAME }}.pg15.linux_arm64
+          tar -czvf steampipe_postgres_${{ env.PLUGIN_NAME }}.pg15.linux_arm64.tar.gz steampipe_postgres_${{ env.PLUGIN_NAME }}.pg15.linux_arm64
+
+      - name: Save Linux Build Artifact - ARM64
         uses: actions/upload-artifact@v3
         with:
           name: steampipe_postgres_${{ env.PLUGIN_NAME }}.pg15.linux_arm64.tar.gz
@@ -423,8 +519,11 @@ jobs:
   build-postgres-15-fdw-osx-amd64:
     name: Build Postgres 15 FDW for Darwin - AMD64
     needs: get-version
-    runs-on: macos-latest
+    runs-on: macos-13
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -510,6 +609,9 @@ jobs:
     needs: get-version
     runs-on: macos-14
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -598,6 +700,9 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -640,29 +745,38 @@ jobs:
       group: steampipe-darwin-arm-runners
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
           echo $plugin_name
           echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV
+
       - name: Check out steampipe-sqlite-extension
         uses: actions/checkout@v3
         with:
           repository: "turbot/steampipe-sqlite"
           ref: main
 
-      - name: Check docker images available in runner
-        run: docker images
+      - name: Setup GoLang
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.21
 
-      - name: Run build script
+      - name: Build steampipe-sqlite-extension
         run: |
-          chmod +x ./scripts/build-linux-arm-sqlite.sh
-          bash ./scripts/build-linux-arm-sqlite.sh ${{ env.PLUGIN_NAME }}
-      
-      - name: Check if binaries are available
-        run: ls -l $GITHUB_WORKSPACE
+          pwd
+          ls -ltr
+          make build plugin=${{ env.PLUGIN_NAME }}
+          ls -ltr
 
-      - name: Save Linux Build Artifact - AMD64
+      - name: Zip and rename the steampipe_sqlite_${{ env.PLUGIN_NAME }}.so
+        run: |-
+          tar -czvf steampipe_sqlite_${{ env.PLUGIN_NAME }}.linux_arm64.tar.gz steampipe_sqlite_${{ env.PLUGIN_NAME }}.so
+
+      - name: Save Linux Build Artifact - ARM64
         uses: actions/upload-artifact@v3
         with:
           name: steampipe_sqlite_${{ env.PLUGIN_NAME }}.linux_arm64.tar.gz
@@ -672,9 +786,12 @@ jobs:
   build-sqlite-extension-osx-amd64:
     name: Build SQLite Extension for Darwin - AMD64
     needs: get-version
-    runs-on: macos-latest
+    runs-on: macos-13
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -716,6 +833,9 @@ jobs:
     runs-on: macos-14
 
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -1001,6 +1121,9 @@ jobs:
     runs-on: ubuntu-latest
     needs: build-draft-release
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -1069,11 +1192,14 @@ jobs:
             exit 1  # This exits the step with an error status, failing the job
           fi
 
-  check-installation-darwin:
-    name: Check Installation(Darwin)
+  check-installation-darwin-arm64:
+    name: Check Installation(Darwin ARM64)
     runs-on: macos-latest
     needs: build-draft-release
     steps:
+      - name: Check architecture
+        run: uname -a
+
       - name: Set environment variables
         run: |
           plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
@@ -1135,3 +1261,74 @@ jobs:
             echo "Version does not match. Expected was $EXPECTED_OUTPUT, but got $COMMAND_OUTPUT."
             exit 1  # This exits the step with an error status, failing the job
           fi
+
+  check-installation-darwin-amd64:
+    name: Check Installation(Darwin AMD64)
+    runs-on: macos-13
+    needs: build-draft-release
+    steps:
+      - name: Check architecture
+        run: uname -a
+
+      - name: Set environment variables
+        run: |
+          plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
+          echo $plugin_name
+          echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV
+
+      - name: Get latest version tag
+        run: |-
+          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+          echo "Version: ${VERSION}"
+
+      - name: Install PostgreSQL14
+        run: brew install postgresql@14
+
+      - name: Start PostgreSQL service
+        run: brew services start postgresql@14
+
+      - name: Check pg_config version
+        run: pg_config --version
+
+      - name: Download and install Postgres FDW
+        run: |-
+          curl -fsSL -o install_postgres_fdw.sh https://steampipe.io/install/postgres.sh
+          echo | sudo -E TERM=xterm bash install_postgres_fdw.sh ${{ env.PLUGIN_NAME }} latest 2>/dev/null
+          rm -f install_postgres_fdw.sh
+
+      - name: Configure PostgreSQL
+        run: |-
+          psql -d postgres -c "CREATE EXTENSION IF NOT EXISTS steampipe_postgres_${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "CREATE SERVER steampipe_${{ env.PLUGIN_NAME }} FOREIGN DATA WRAPPER steampipe_postgres_${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "CREATE SCHEMA ${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "IMPORT FOREIGN SCHEMA ${{ env.PLUGIN_NAME }} FROM SERVER steampipe_${{ env.PLUGIN_NAME }} INTO ${{ env.PLUGIN_NAME }};"
+          psql -d postgres -c "SELECT * FROM pg_extension;"
+
+      - name: Download and install SQLite Extension
+        run: |-
+          echo | TERM=xterm bash <(curl -fsSL https://steampipe.io/install/sqlite.sh) ${{ env.PLUGIN_NAME }} latest 2>/dev/null
+
+      - name: Download and install Export Tool
+        run: |-
+          curl -fsSL -o install_export.sh https://steampipe.io/install/export.sh
+          echo | sudo -E TERM=xterm bash install_export.sh ${{ env.PLUGIN_NAME }} latest 2>/dev/null
+          rm -f install_export.sh
+
+      - name: Test Export Tool
+        run: |
+          # Define the expected output based on environment variables and inputs
+          EXPECTED_OUTPUT="steampipe_export_${{ env.PLUGIN_NAME }} ${VERSION}"
+          echo "Expected version output: $EXPECTED_OUTPUT"
+          
+          # Execute the command to get the actual version output
+          COMMAND_OUTPUT=$(steampipe_export_${{ env.PLUGIN_NAME }} --version)
+          echo "Actual command output version: $COMMAND_OUTPUT"
+          
+          # Compare the actual output with the expected output
+          if [ "$COMMAND_OUTPUT" == "$EXPECTED_OUTPUT" ]; then
+            echo "Version matches."
+          else
+            echo "Version does not match. Expected was $EXPECTED_OUTPUT, but got $COMMAND_OUTPUT."
+            exit 1  # This exits the step with an error status, failing the job
+          fi
+        
